### ISSUE TITLE
Question about `srl-eval.pl` on arabic dataset

### ISSUE THREAD

**Issue by chaojiang06** [pmulcaire/rosita#1]
Hi, thanks for the great repo! 

I was working on training SRL models on the Arabic part of ontonotes using AllenNLP. I follow the [instruction](http://conll.cemantix.org/2012/data.html) here to do the pre-processing. I also remove the diacritics as [describe](https://www.aclweb.org/anthology/N19-1392.pdf) in your paper. The training part can successfully be finished. 

However, the program crashes at the validation step. The validation code will finally call the conll 2005 evaluation script `srl-eval.pl` to compute metrics such as precision / recall / f1, and `srl-eval.pl` report an error: `phrase_set->load_SE_tagging: some phrases are unclosed!` . There is a similar issue report [here](https://github.com/allenai/allennlp/issues/4102#issuecomment-626924381).

I was thinking this bug is due to there are some complex or wrong labels in the gold label that `srl-eval.pl` can't handle. I was wondering have you experience similar problems?

Any help will be appreciated!

**Comment by pmulcaire** [comment]
Hi, yes, if the gold labels contain errors, they might not be able to be evaluated. 

In this case, I would say just remove the sentence in question from your validation data, or edit the label to fix the issue.
